name: "action to print memory info of a docker container"
description: "Github Container Action to display the memory information of the docker container for this container action"
author: "Colin But"
inputs:
  myInput:
    description: "message to display"
    required: true
    default: "Colin"
outputs:
  myOutput:
    description: "total memory"
runs:
  using: "docker"
  image: "Dockerfile"
